servers:
  - displayName: "Server1"
    jmxServiceUrl: "service:jmx:t3://localhost:7001/jndi/weblogic.management.mbeanservers.runtime"
    username: "weblogic"
    password: "admin123"
    jmx.remote.protocol.provider.pkgs: "weblogic.management.remote"
    jmx.remote.x.request.waiting.timeout: 10000

    mbeans:
      - objectName: "com.bea:ServerRuntime=AdminServer,Name=AdminServer,Type=JVMRuntime"
        metricPathFromObjectNameProperties: ["Name", "Type"]
        metrics:
          include:
            - HeapSizeMax : "HeapSizeMax"
            - HeapSizeCurrent : "HeapSizeCurrent"
            - HeapFreeCurrent : "HeapFreeCurrent"

      - objectName: "com.bea:ServerRuntime=AdminServer,Name=AdminServer,Type=JTARecoveryRuntime,JTARuntime=JTARuntime"
        metricPathFromObjectNameProperties: ["Name", "Type", "JTARuntime"]
        metrics:
          include:
            - InitialRecoveredTransactionTotalCount: "InitialRecoveredTransactionTotalCount"


# number of concurrent tasks
numberOfThreads: 3



metricPrefix: "Custom Metrics|WebLogic|"